spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: MNz1uPMfAw_J9NGiUROb
            client-secret: DUUqPHkPb8
          kakao:
            clientId: 1ee8debcc5daaa5d20a762284acb7260
          google:
            clientId: 400392687659-9kdf3qpdci5drsils18c7pdskrtjg97t.apps.googleusercontent.com
            client-secret: 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
          facebook:
            clientId: 793047875746625
            client-secret: d6373888ab3f2ea7f304b5781e85ebc2