spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: MNz1uPMfAw_J9NGiUROb
            client-secret: DUUqPHkPb8
          kakao:
            clientId: 1ee8debcc5daaa5d20a762284acb7260